name: resetaplus
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  gradient_borders: ^1.0.1
  gradient_icon: ^2.0.9
  mysql_client: ^0.0.27
  mysql1: 0.20.0
  http: ^1.2.0
  crypto: ^3.0.1
  encrypt: ^5.0.0
  email_validator: "^2.1.17"
  carousel_slider: ^5.0.0
  intl: ^0.19.0
  flutter_dotenv: ^5.2.1
  shared_preferences: ^2.3.2
  dropdown_search: ^6.0.1
  searchfield: ^1.1.7
  qr_flutter: ^4.0.0 
  path_provider: ^2.0.9  



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo_ResetaPlus.png
    - assets/.env
  fonts:
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat/static/Montserrat-Regular.ttf
        - asset: fonts/Montserrat/static/Montserrat-Italic.ttf
          # style: TextStyle(fontStyle: FontStyle.italic)
          style: italic
        - asset: fonts/Montserrat/static/Montserrat-Bold.ttf
          # fontWeight: FontWeight.w700
          weight: 700
